"""Add ingestion tables

Revision ID: 6adfb8301658
Revises: 
Create Date: 2026-01-10 23:41:35.998067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '6adfb8301658'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_ingestion_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('target_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('records_ingested', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_ingestion_log_id'), 'data_ingestion_log', ['id'], unique=False)
    op.create_index(op.f('ix_data_ingestion_log_source'), 'data_ingestion_log', ['source'], unique=False)
    op.create_index(op.f('ix_data_ingestion_log_target_date'), 'data_ingestion_log', ['target_date'], unique=False)
    op.create_table('ice_concentrations_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('concentration', sa.Float(), nullable=False),
    sa.Column('resolution_km', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_ice_concentrations_daily_geometry', 'ice_concentrations_daily', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_ice_concentrations_daily_date'), 'ice_concentrations_daily', ['date'], unique=False)
    op.create_index(op.f('ix_ice_concentrations_daily_id'), 'ice_concentrations_daily', ['id'], unique=False)
    op.create_table('ice_drift_vectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('start_point', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('end_point', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('velocity_x', sa.Float(), nullable=True),
    sa.Column('velocity_y', sa.Float(), nullable=True),
    sa.Column('velocity_magnitude', sa.Float(), nullable=True),
    sa.Column('resolution_km', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_ice_drift_vectors_end_point', 'ice_drift_vectors', ['end_point'], unique=False, postgresql_using='gist')
    # op.create_index('idx_ice_drift_vectors_start_point', 'ice_drift_vectors', ['start_point'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_ice_drift_vectors_end_date'), 'ice_drift_vectors', ['end_date'], unique=False)
    op.create_index(op.f('ix_ice_drift_vectors_id'), 'ice_drift_vectors', ['id'], unique=False)
    op.create_index(op.f('ix_ice_drift_vectors_start_date'), 'ice_drift_vectors', ['start_date'], unique=False)
    op.create_table('ice_extent_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('area_km2', sa.Float(), nullable=True),
    sa.Column('perimeter_km', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_ice_extent_daily_geometry', 'ice_extent_daily', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_ice_extent_daily_date'), 'ice_extent_daily', ['date'], unique=False)
    op.create_index(op.f('ix_ice_extent_daily_id'), 'ice_extent_daily', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ice_extent_daily_id'), table_name='ice_extent_daily')
    op.drop_index(op.f('ix_ice_extent_daily_date'), table_name='ice_extent_daily')
    # op.drop_index('idx_ice_extent_daily_geometry', table_name='ice_extent_daily', postgresql_using='gist')
    op.drop_table('ice_extent_daily')
    op.drop_index(op.f('ix_ice_drift_vectors_start_date'), table_name='ice_drift_vectors')
    op.drop_index(op.f('ix_ice_drift_vectors_id'), table_name='ice_drift_vectors')
    op.drop_index(op.f('ix_ice_drift_vectors_end_date'), table_name='ice_drift_vectors')
    # op.drop_index('idx_ice_drift_vectors_start_point', table_name='ice_drift_vectors', postgresql_using='gist')
    # op.drop_index('idx_ice_drift_vectors_end_point', table_name='ice_drift_vectors', postgresql_using='gist')
    op.drop_table('ice_drift_vectors')
    op.drop_index(op.f('ix_ice_concentrations_daily_id'), table_name='ice_concentrations_daily')
    op.drop_index(op.f('ix_ice_concentrations_daily_date'), table_name='ice_concentrations_daily')
    # op.drop_index('idx_ice_concentrations_daily_geometry', table_name='ice_concentrations_daily', postgresql_using='gist')
    op.drop_table('ice_concentrations_daily')
    op.drop_index(op.f('ix_data_ingestion_log_target_date'), table_name='data_ingestion_log')
    op.drop_index(op.f('ix_data_ingestion_log_source'), table_name='data_ingestion_log')
    op.drop_index(op.f('ix_data_ingestion_log_id'), table_name='data_ingestion_log')
    op.drop_table('data_ingestion_log')
    # ### end Alembic commands ###
